### PR TITLE
feat: add popular projects to ecosystem-ci

### PR DESCRIPTION
**Pull request by sheremet-va**

### CODE REVIEW

**Comment by sheremet-va** [comment]
@AriPerkkio is it possible to run them here before merging?

**Comment by AriPerkkio** [comment]
- https://github.com/vitest-dev/vitest-ecosystem-ci/actions/runs/8829575584
- https://github.com/vitest-dev/vitest-ecosystem-ci/actions/runs/8829573458

**Comment by sheremet-va** [comment]
Hm, @AriPerkkio excalidraw should work fine 🤔 I don't understand why it's failing :(

**Comment by AriPerkkio** [comment]
> Hm, @AriPerkkio excalidraw should work fine 🤔 I don't understand why it's failing :(

I've been looking into this and don't really know what's going on. Corepack seems to be throwing error `Usage Error: This project is configured to use pnpm`, even with following changes:

```diff
export async function test(options: RunOptions) {
	await runInRepo({
		...options,
		branch: 'master',
		repo: 'excalidraw/excalidraw',
		test: 'test:app',
+		agent: "yarn",
	})
}
```

I think we need to ask `vite-ecosystem-ci` maintainers for help. It might be good to move `excalidraw` to separate PR and merge this one without it.

**Comment by AriPerkkio** [comment]
`excalidraw` doesn't have `packageManager` defined in `package.json`. This command fails:

https://github.com/vitest-dev/vitest-ecosystem-ci/blob/602f008f4a5f35da1ad3c01da939b5836fee80f9/utils.ts#L427

**Comment by AriPerkkio** [comment]
https://github.com/vitest-dev/vitest-ecosystem-ci/actions/runs/8858388425/job/24326965801

**Comment by sheremet-va** [comment]
effect is failing, but they are aware of the issue, and it should be fixed soon

**Pull request merged**
